# Generated by Django 6.0.5 on 2026-05-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_sede_direccion_alter_usuario_rol_miembro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientofinanciero',
            name='tipo',
            field=models.CharField(choices=[('diezmo', 'Diezmo'), ('ofrenda', 'Ofrenda'), ('primicia', 'Primicia'), ('accion_gracias', 'Acción de Gracias'), ('gasto', 'Gasto')], max_length=20),
        ),
    ]
